# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'fffff'
    subscriptionId: '02432a48-ad7d-4c09-896d-4fa83f18231f'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'testing1'
    location: 'Central US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/superapgit/test/main/web_app/azuredeploy.json'
    overrideParameters: '-projectName apoorvavijeesh'
    deploymentMode: 'Incremental'
    deploymentName: 'testdeploy'